# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
    imports =[(modulesPath + "/installer/scan/not-detected.nix")];
    boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [];
    boot.kernelModules = [];
    boot.extraModulePackages = [];

    fileSystems."/" =
    { device "/dev/disk/by-uuid/28b7aa44-1b34-4e45-b0b5-04e8ca48625a";
      fsType = "ext4";
    };
    fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/45DD-D342";
      fsType="vfat";
    };

    swapDevices = [ { device = "/deu/disk/by-label/swap"; } ];
    networking.useDHCP = lib.mkDefault true;
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    virtualisation.virtualbox.guest.enable = true;
}